/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as StatsScriptDotjsRouteImport } from './routes/stats/script[.]js'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as StatsApiSendRouteImport } from './routes/stats/api/send'

const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsScriptDotjsRoute = StatsScriptDotjsRouteImport.update({
  id: '/stats/script.js',
  path: '/stats/script.js',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsApiSendRoute = StatsApiSendRouteImport.update({
  id: '/stats/api/send',
  path: '/stats/api/send',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/uses': typeof UsesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/stats/script.js': typeof StatsScriptDotjsRoute
  '/blog/': typeof BlogIndexRoute
  '/stats/api/send': typeof StatsApiSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/uses': typeof UsesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/stats/script.js': typeof StatsScriptDotjsRoute
  '/blog': typeof BlogIndexRoute
  '/stats/api/send': typeof StatsApiSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/uses': typeof UsesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/stats/script.js': typeof StatsScriptDotjsRoute
  '/blog/': typeof BlogIndexRoute
  '/stats/api/send': typeof StatsApiSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/rss.xml'
    | '/uses'
    | '/blog/$slug'
    | '/stats/script.js'
    | '/blog/'
    | '/stats/api/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/rss.xml'
    | '/uses'
    | '/blog/$slug'
    | '/stats/script.js'
    | '/blog'
    | '/stats/api/send'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/rss.xml'
    | '/uses'
    | '/blog/$slug'
    | '/stats/script.js'
    | '/blog/'
    | '/stats/api/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  UsesRoute: typeof UsesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  StatsScriptDotjsRoute: typeof StatsScriptDotjsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  StatsApiSendRoute: typeof StatsApiSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/script.js': {
      id: '/stats/script.js'
      path: '/stats/script.js'
      fullPath: '/stats/script.js'
      preLoaderRoute: typeof StatsScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/api/send': {
      id: '/stats/api/send'
      path: '/stats/api/send'
      fullPath: '/stats/api/send'
      preLoaderRoute: typeof StatsApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  UsesRoute: UsesRoute,
  BlogSlugRoute: BlogSlugRoute,
  StatsScriptDotjsRoute: StatsScriptDotjsRoute,
  BlogIndexRoute: BlogIndexRoute,
  StatsApiSendRoute: StatsApiSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
